### ISSUE TITLE
`this.container` has no replacement

### ISSUE THREAD

**Issue by kellyselden** [simonihmig/ember-test-helpers-codemod#19]
Taken from https://github.com/DockYard/ember-route-action-helper#overriding-route-action-for-integration-tests

```js
this.container.registry.registrations['helper:route-action'] = helper(() => () => {});
```

is missed in the codemod. `this.container` is undefined after codemod. I manually updated with

```js
this.owner.__registry__.registrations['helper:route-action'] = helper(() => () => {});
```

This codemod could be updated with this translation, or maybe there is a better translation than what I came up with? cc @rwjblue

**Comment by rwjblue** [comment]
Hmm, any reason not to update that to `this.owner.register('helper:route-action', Ember.Helper.helper(() => {}))`?  I'm pretty hesitant to add anything around `__registry__` to this codemod...

**Comment by simonihmig** [comment]
Hm, I agree with @rwjblue, using anything `__` makes me feel slightly uncomfortable! 😉

Also I wonder if that is really within the scope of this codemod, because...

1. It is not really about test helpers, right?
2. It is a 3rd party thing. Also there are a few addons supplying their own test helpers, so I am a bit hesitant to start supporting any or all of them here (for those that need to be fixed)
3. this codemod doesn't handle any changes related to the container/owner so far. AFAIK `ember-qunit-codemod` does a few owner related transforms, so might be a better place to put this? But 2. still applies to it as well...

**Comment by kellyselden** [comment]
Oh shoot. This is the wrong repo. Should have been `ember-qunit-codemod`. Sorry! Downside of ember-cli-update running all codemods, you have to think harder about where the changes come from :(
